8 1 1
ONSdigital/sdg_data_updates pull request #172
Opened 2023-05-15 07:11 UTC by uzzelk

2023-05-15 07:12 UTC, uzzelk commented
[Michael Nairn Code review for 8-1-1.docx](https://github.com/ONSdigital/sdg_data_updates/files/11475058/Michael.Nairn.Code.review.for.8-1-1.docx)

2023-05-15 10:21 UTC, MichaelGNairn requested changes
Thanks for adding review Katie. 

As noted, not sure why your code didn't work as it looks like it should have!

Maybe a quick call later this week, if easier.

2023-05-17 08:28 UTC, MichaelGNairn commented
Added the below to end of checks file.

[09:24] Nairn, Michael




## Session Info

```{r}

pander(sessionInfo())

```

2023-05-17 08:30 UTC, MichaelGNairn approved these changes

2023-05-17 09:48 UTC, merged